// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using bank.Data;

#nullable disable

namespace bank.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20251201223749_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("bank.Models.Agence", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Code");

                    b.ToTable("agences", (string)null);
                });

            modelBuilder.Entity("bank.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgenceCode")
                        .HasColumnType("text");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenceCode");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("bank.Models.Compte", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Code"));

                    b.Property<string>("ClientNumero")
                        .IsRequired()
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Solde")
                        .HasColumnType("double precision");

                    b.Property<string>("TypeCompte")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Code");

                    b.HasIndex("ClientNumero")
                        .IsUnique();

                    b.ToTable("comptes", (string)null);

                    b.HasDiscriminator<string>("TypeCompte").HasValue("Base");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("bank.Models.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompteDestinationId")
                        .HasColumnType("integer");

                    b.Property<int>("CompteSourceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Montant")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompteDestinationId");

                    b.HasIndex("CompteSourceId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("bank.Models.CompteCourant", b =>
                {
                    b.HasBaseType("bank.Models.Compte");

                    b.Property<double>("Decouvert")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Courant");
                });

            modelBuilder.Entity("bank.Models.CompteEpargne", b =>
                {
                    b.HasBaseType("bank.Models.Compte");

                    b.Property<double>("TauxInteret")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("Epargne");
                });

            modelBuilder.Entity("bank.Models.ComptePayant", b =>
                {
                    b.HasBaseType("bank.Models.Compte");

                    b.HasDiscriminator().HasValue("Payant");
                });

            modelBuilder.Entity("bank.Models.Client", b =>
                {
                    b.HasOne("bank.Models.Agence", null)
                        .WithMany("Clients")
                        .HasForeignKey("AgenceCode");
                });

            modelBuilder.Entity("bank.Models.Compte", b =>
                {
                    b.HasOne("bank.Models.Client", "Client")
                        .WithOne("Compte")
                        .HasForeignKey("bank.Models.Compte", "ClientNumero")
                        .HasPrincipalKey("bank.Models.Client", "Numero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("bank.Models.Operation", b =>
                {
                    b.HasOne("bank.Models.Compte", "CompteDestination")
                        .WithMany()
                        .HasForeignKey("CompteDestinationId");

                    b.HasOne("bank.Models.Compte", "CompteSource")
                        .WithMany()
                        .HasForeignKey("CompteSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompteDestination");

                    b.Navigation("CompteSource");
                });

            modelBuilder.Entity("bank.Models.Agence", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("bank.Models.Client", b =>
                {
                    b.Navigation("Compte");
                });
#pragma warning restore 612, 618
        }
    }
}
